### PR TITLE
Kin starter java

### PR DESCRIPTION
**Pull request by xingyi0201**

### CODE REVIEW

**Comment by hitwill** [comment]
Thanks @xingyi0201 I sent some details requesting some changes. (I will close this PR since the changes were significant in terms of directory structure)

**Comment by hitwill** [comment]
@beeman I recommend we close this PR (I don't have the auth)

**Review by beeman — CHANGES_REQUESTED** [review]
I have created a new repo for the starter app. Please don't break the website 😅

**Comment by xingyi0201** [comment]
Sorry for my misunderstood.

I will figure out them asap.

Thank you,
Xing

**Pull request closed without merging**
